### ISSUE TITLE
Using `dplyr::join_by` in joins doesn't work

### ISSUE THREAD

**Issue by Moohan** [elbersb/tidylog#65] opened 2024-05-03 10:32 UTC
When using the new(ish) `dplyr::join_by` in a join e.g.

``` r 
data |>
  left_join(lookup, by = join_by(name1 == name2))
``` 

We get an error, being caused by `tidylog::left_join()` not supporting the new object type.

``` r
Error in `dplyr::common_by()`:
! `by` must be a (named) character vector, list, or NULL for natural joins (not recommended in production code),
  not a <dplyr_join_by> object.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by elbersb** [comment] 2024-05-07 07:26
Can you try to install the Github version? `devtools::install_github("elbersb/tidylog")`
This was reported before and fixed in #58.
If the problem is still there, please provide a [reprex](https://reprex.tidyverse.org).

**Comment by rkb965** [comment] 2024-05-07 17:57
love this package. I understand that you don't intend to do further development on it, and I really appreciate that you nonetheless fixed the "join_by" error. are you planning on submitting this fix to CRAN or will it only be in the dev version?

**Comment by elbersb** [comment] 2024-05-08 08:42
Just released a new version on CRAN. (The last release was mid-2020, so a new one was definitely overdue...)

**Comment by elbersb** [comment] 2024-05-12 15:33
I assume this fixed the issue, feel free to reopen if not

**Closed by elbersb** 2024-05-12 15:33 UTC
